/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package publictransportation.view;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import publictransportation.control.EmailValidator;
import publictransportation.control.Payment_Manager;
import publictransportation.*;
import publictransportation.control.EmailSender;
import publictransportation.models.PayPalPayment;
import publictransportation.models.Set_Of_Costs;
import publictransportation.models.Set_Of_Offers;
import publictransportation.models.Set_Of_Tokens;
import publictransportation.models.Token;

/**
 *
 * @author Kavindu Gayashan
 */
public class CheckTicketDetails extends javax.swing.JFrame {

    
    Set_Of_Tokens setOfTokens=new Set_Of_Tokens();
    Payment_Manager paymentManager= Payment_Manager.getInstance();
    Float jCost;
    /**
     * Creates new form CheckTicketDetails
     */
    public CheckTicketDetails(ManageJourney window,String source, String destination, int jType) {
        initComponents();
        validLbl.setText("");
        validLbl1.setText("");
        
        paymentManager.refreshPaymentManager();
        
        
        Float tCost= paymentManager.getTicketPrice(source, destination);
        Float discount= paymentManager.getAppliedDiscount();
        jCost=paymentManager.lookupCost(source, destination);
        
        fromStopLbl.setText(source);
        toStopLbl.setText(destination);
        if(jType==1){
            ticketTypeLbl.setText("Single");
            
        }else{
            ticketTypeLbl.setText("Return");
            jCost=jCost*2;
        }
        
        ticketPriceLbl.setText(tCost.toString());
        discountLbl.setText(discount.toString());
        totalLbl.setText(jCost.toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fromStopLbl = new javax.swing.JLabel();
        toStopLbl = new javax.swing.JLabel();
        ticketTypeLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ticketPriceLbl = new javax.swing.JLabel();
        discountLbl = new javax.swing.JLabel();
        totalLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        paypalIDTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        validLbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        validLbl1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        paypalPasswordTxt = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        tokenLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1280, 720));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Doppio One", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("#TravelAnywhere");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("From                  :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("To                      :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Ticket type         :");

        fromStopLbl.setForeground(new java.awt.Color(102, 102, 102));
        fromStopLbl.setText("From              :");

        toStopLbl.setForeground(new java.awt.Color(102, 102, 102));
        toStopLbl.setText("To                   :");

        ticketTypeLbl.setForeground(new java.awt.Color(102, 102, 102));
        ticketTypeLbl.setText("Ticket type   :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Ticket price         :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Discount             :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Total amount      :");

        ticketPriceLbl.setForeground(new java.awt.Color(102, 102, 102));
        ticketPriceLbl.setText("Ticket price   :");

        discountLbl.setForeground(new java.awt.Color(102, 102, 102));
        discountLbl.setText("Discount   :");

        totalLbl.setForeground(new java.awt.Color(102, 102, 102));
        totalLbl.setText("Total  :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("PayPal ID            :");

        paypalIDTxt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                paypalIDTxtCaretUpdate(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("User Email      :");

        emailTxt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                emailTxtCaretUpdate(evt);
            }
        });

        validLbl.setForeground(new java.awt.Color(102, 102, 102));
        validLbl.setText("validation");

        jButton1.setText("Confirm and Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        validLbl1.setForeground(new java.awt.Color(102, 102, 102));
        validLbl1.setText("validation");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("PayPal Password :");

        paypalPasswordTxt.setText("jPasswordField1");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Your token is   :");

        tokenLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tokenLbl.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ticketTypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(toStopLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                            .addComponent(fromStopLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ticketPriceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(discountLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(totalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(paypalIDTxt)
                                            .addComponent(emailTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                            .addComponent(validLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(validLbl1, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(paypalPasswordTxt)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(tokenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(114, 114, 114)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(paypalIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fromStopLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(toStopLbl)
                                .addGap(18, 18, 18)
                                .addComponent(ticketTypeLbl)
                                .addGap(18, 18, 18)
                                .addComponent(ticketPriceLbl)
                                .addGap(18, 18, 18)
                                .addComponent(discountLbl)
                                .addGap(18, 18, 18)
                                .addComponent(totalLbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validLbl1)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(paypalPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(validLbl)
                        .addGap(62, 62, 62)
                        .addComponent(jButton1)
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(tokenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailTxtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_emailTxtCaretUpdate
        if(EmailValidator.isValid(emailTxt.getText())){
            validLbl.setText("Valid");
            validLbl.setForeground(Color.GREEN);
        }else{
            validLbl.setText("Invalid");
            validLbl.setForeground(Color.RED);
        }
    }//GEN-LAST:event_emailTxtCaretUpdate

    private void deserializeSetOfTokens(){
        //Deserializing Set of tokens
        try{
            System.out.println("Deserializing Set of tokens");
            FileInputStream fileInputTokens= new FileInputStream("Tokens.ser");
            ObjectInputStream objectInputTokens= new ObjectInputStream(fileInputTokens);
            setOfTokens=(Set_Of_Tokens) objectInputTokens.readObject();
            objectInputTokens.close();
            fileInputTokens.close();

            System.out.println("Deserialized Set of tokens");
        }
        catch(Exception e){
            System.out.println("Couldn't deserialize Set of tokens Error:"+e.getMessage());
        }
    }
    
    private void serializeSetOfTokens(){
        //Serialization
        System.out.println("Serializing Set of Tokens");
        try{
            FileOutputStream fileOutputToken=new FileOutputStream("Tokens.ser");
            ObjectOutputStream objectOutputToken=new ObjectOutputStream(fileOutputToken);
            objectOutputToken.writeObject(setOfTokens);
            objectOutputToken.flush();
            objectOutputToken.close();
            objectOutputToken.close();
            
            System.out.println("Serialized!");
        }
        catch(Exception e){
            System.out.println("Couldn't serialize.");
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Checking if the email field and the Paypal ID field is valid
        if(validLbl.getText().equals("Valid") && validLbl1.getText().equals("Valid")){
            PayPalPayment payment=new PayPalPayment(paypalIDTxt.getText(), paypalPasswordTxt.getPassword().toString(), jCost);

            //Validationg the payment via Payment manager
            if(paymentManager.validatePayment(payment)){
                Token token=new Token(fromStopLbl.getText(), toStopLbl.getText());
                Integer tokenid=token.getToken_ID();
                
                deserializeSetOfTokens();
                
                setOfTokens.addToken(token);
                
                if(SendEmail(tokenid,emailTxt.getText())){
                    JOptionPane.showMessageDialog(this, "Please check your email "+emailTxt.getText());
                    tokenLbl.setText(tokenid.toString());
                }else{
                    JOptionPane.showMessageDialog(this, "Something went wrong. Please note down the token number for further use.");
                    tokenLbl.setText(tokenid.toString());
                }
                
                serializeSetOfTokens();
                
            }
        
        }else{
            JOptionPane.showMessageDialog(this, "Paypal ID and Email has to be valid. Please check and try again.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public Boolean SendEmail(int tokenID,String to){
        
        EmailSender emailSender=new EmailSender();
        
        String sub="Your token is ready";
        String msg="Hello, \n This is an automated message from TravelAnywhere System. \n Your Token is "+tokenID;
        try{
            emailSender.send(to,sub,msg);
        }catch(Exception e){
            return false;
        }
        return true;
        
    }
    
    
    private void paypalIDTxtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_paypalIDTxtCaretUpdate
        if(EmailValidator.isValid(paypalIDTxt.getText())){
            validLbl1.setText("Valid");
            validLbl1.setForeground(Color.GREEN);
        }else{
            validLbl1.setText("Invalid");
            validLbl1.setForeground(Color.RED);
        }
    }//GEN-LAST:event_paypalIDTxtCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckTicketDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckTicketDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckTicketDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckTicketDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CheckTicketDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel discountLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel fromStopLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField paypalIDTxt;
    private javax.swing.JPasswordField paypalPasswordTxt;
    private javax.swing.JLabel ticketPriceLbl;
    private javax.swing.JLabel ticketTypeLbl;
    private javax.swing.JLabel toStopLbl;
    private javax.swing.JLabel tokenLbl;
    private javax.swing.JLabel totalLbl;
    private javax.swing.JLabel validLbl;
    private javax.swing.JLabel validLbl1;
    // End of variables declaration//GEN-END:variables
}
